- name: Install rsync
  apt:
    name: rsync

- name: Generate client ssh key
  include_tasks: keygen.yml

- name: Scan server key for known_hosts
  command: 'ssh-keyscan {{ rss_server }}'
  register: key_scan

- name: Add server key to client's known_hosts
  known_hosts:
    name: "{{ rss_server }}"
    key: "{{ key_scan.stdout }}"

- name: Register client with server
  block:
    - name: Create client backup root
      file:
        path: '{{ rss_root }}/{{ client_name }}'
        owner: '{{ rss_user }}'
        state: directory

    - set_fact:
        rsyncd_conf: '{{ rss_root }}/{{ client_name }}.conf'

    - name: Install rsync daemon conf
      template:
        src: rsyncd.j2
        dest: '{{ rsyncd_conf }}'

    - name: Set authorized_keys command
      authorized_key:
        user: '{{ rss_user }}'
        key: '{{ client_pub_key }}'
        key_options: 'command="/usr/bin/rsync --server --daemon --config={{ rsyncd_conf }} .",restrict'
  delegate_to: '{{ rss_server }}'
