- include_vars: client.yml

- name: Create client backup root
  file:
    path: '{{ client_root }}'
    state: directory
  delegate_to: '{{ rss_server }}'
  register: backup_root

- name: Set client backup root ownership
  when: backup_root is changed
  file:
    path: '{{ client_root }}'
    state: directory
    owner: '{{ rss_user }}'
  delegate_to: '{{ rss_server }}'

- name: Install rsync daemon conf
  template:
    src: rsyncd.j2
    dest: '{{ client_rsyncd_conf }}'
  delegate_to: '{{ rss_server }}'

- name: Set authorized_keys command
  authorized_key:
    user: '{{ rss_user }}'
    key: '{{ client_pub_key }}'
    key_options: 'command="/usr/bin/rsync --server --daemon --config={{ client_rsyncd_conf }} .",restrict'
  delegate_to: '{{ rss_server }}'

- name: Add users for uid matching
  user:
    name: '{{ item }}'
    create_home: false
  loop: '{{ client_users | default([]) }}'
  delegate_to: '{{ rss_server }}'

- name: Add groups for uid matching
  group:
    name: '{{ item }}'
  loop: '{{ client_groups | default([]) }}'
  delegate_to: '{{ rss_server }}'
