- name: Ensure client key folder exists
  file:
    path: '{{ client_key_file | dirname }}'
    state: directory
    mode: '700'

- name: Generate ssh key pair
  command: 'ssh-keygen -N "" -f {{ client_key_file }}'
  args:
    creates: '{{ client_key_file }}'

- name: Copy public key
  command: 'cat {{ client_key_file }}.pub'
  register: public_key
- set_fact:
     client_pub_key: '{{ public_key.stdout }}'
