- name: Ensure client key folder exists
  file:
    path: '{{ client_key_file | dirname }}'
    state: directory
    mode: '700'

- name: Generate ssh key pair
  command: 'ssh-keygen -N "" -f {{ client_key_file }}'
  args:
    creates: '{{ client_key_file }}'
  register: keygen

- name: Copy public key
  command: 'ssh-keygen -y -f {{ client_key_file }}'
  register: public_key
  changed_when: keygen is changed
- set_fact:
     client_pub_key: '{{ public_key.stdout }}'
