- name: Scan server key for known_hosts
  command: 'ssh-keyscan {{ rss_server_host }}'
  register: key_scan

- name: Add server key to client's known_hosts
  known_hosts:
    name: "{{ rss_server_host }}"
    key: "{{ key_scan.stdout }}"
